import { Integration } from './types';

// Helper to generate color from string
const getColor = (str: string) => {
  const colors = [
    'bg-brand-500', 'bg-blue-500', 'bg-green-500', 'bg-purple-500', 
    'bg-orange-500', 'bg-teal-500', 'bg-indigo-500', 'bg-pink-500'
  ];
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash);
  }
  return colors[Math.abs(hash) % colors.length];
};

const POPULAR_NAMES = new Set([
  "Salesforce", "Microsoft Dynamics", "QuickBooks", "SAP", "Oracle",
  "NetSuite", "Hubspot", "Zoho", "Workday", "Xero", "ADP", "Shopify",
  "Zendesk", "Infor", "Acumatica", "Epicor", "ServiceNow", "Jira",
  "Monday.com", "Paychex", "Sage", "Microsoft Business Central", "Bill.com",
  "Stripe", "Square", "Rippling", "Gusto", "BambooHR"
]);

const rawData = [
  { name: "Salesforce", description: "Customer relationship management platform", logo_url: "https://img.logo.dev/salesforce.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Microsoft Access", description: "Database management system", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Microsoft Azure Database", description: "Cloud database services", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Microsoft Business Central", description: "Cloud-based ERP for SMBs", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Microsoft Fabric", description: "Unified analytics platform", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Microsoft Great Plains", description: "Business accounting software", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Microsoft Dynamics", description: "Customer relationship management platform | Enterprise resource planning software | Field service management solution | Financial management software | Cloud ERP for enterprise | Business management solution for SMBs", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "QuickBooks", description: "Desktop accounting software for small business | Advanced accounting for growing businesses | Cloud-based accounting software", logo_url: "https://img.logo.dev/intuit.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "SAP", description: "ERP for small and midsize businesses | Cloud ERP for midsize companies | Travel and expense management | Core ERP functionality of SAP | In-memory database and application platform | SAP system (possibly S/4HANA)", logo_url: "https://img.logo.dev/sap.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Oracle", description: "Enterprise performance management software | Enterprise software and database solutions | Cloud-based ERP suite | Enterprise business suite | Cloud POS for hospitality", logo_url: "https://img.logo.dev/oracle.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Amazon Seller Central", description: "Platform for managing Amazon marketplace sales", logo_url: "https://img.logo.dev/amazon.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Google Cloud Storage", description: "Cloud object storage service", logo_url: "https://img.logo.dev/google.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "JMS (Java Message Service)", description: "Messaging standard for Java applications", logo_url: "", category: "IT & Data" },
  { name: "Sage", description: "Accounting and business management ERP | Business management software for mid-market | ERP for distribution and manufacturing | Construction and real estate ERP | Enterprise business management software | Accounting software for Canadian businesses | Payroll management software | Accounting software for UK businesses | Accounting software for US small businesses | CRM and contact management software | Fixed asset management software | Cloud-based business management suite | Accounting software for small businesses | Cloud-based financial management software | Cloud HR and people management | Enterprise management solution", logo_url: "https://img.logo.dev/sage.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "NetSuite", description: "Cloud-based ERP software suite | Cloud professional services automation | Cloud planning and budgeting solution", logo_url: "https://img.logo.dev/netsuite.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Hubspot", description: "Inbound marketing and sales CRM platform", logo_url: "https://img.logo.dev/hubspot.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Zoho", description: "Suite of business software applications | Customer relationship management software | Customer support and help desk software | Inventory and order management software | Cloud HR management software", logo_url: "https://img.logo.dev/zoho.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Business Suite" },
  { name: "Workday", description: "Enterprise cloud applications for finance and HR", logo_url: "https://img.logo.dev/workday.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Xero", description: "Cloud-based accounting software for small business", logo_url: "https://img.logo.dev/xero.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "ADP", description: "Human capital management and payroll solutions", logo_url: "https://img.logo.dev/adp.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Shopify", description: "E-commerce platform for online stores", logo_url: "https://img.logo.dev/shopify.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Zendesk", description: "Customer service and engagement platform", logo_url: "https://img.logo.dev/zendesk.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Customer Service" },
  { name: "Infor", description: "Cloud ERP for discrete manufacturing | Enterprise resource planning software suite | Accounting software for small to mid-sized businesses | Cloud ERP for manufacturing and distribution | Manufacturing ERP software | ERP for mid-market manufacturers", logo_url: "https://img.logo.dev/infor.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Acumatica", description: "Cloud-based ERP software for growing businesses", logo_url: "https://img.logo.dev/acumatica.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Epicor", description: "ERP software for manufacturing and distribution", logo_url: "https://img.logo.dev/epicor.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Pipedrive", description: "Sales CRM and pipeline management", logo_url: "https://img.logo.dev/pipedrive.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Paychex", description: "Payroll and HR solutions", logo_url: "https://img.logo.dev/paychex.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "ServiceNow", description: "Cloud-based IT service management", logo_url: "https://img.logo.dev/servicenow.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Monday.com", description: "Work operating system for team collaboration", logo_url: "https://img.logo.dev/monday.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Jira", description: "Project and issue tracking software", logo_url: "https://img.logo.dev/atlassian.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "3PL Net", description: "Third-party logistics warehouse management system for supply chain operations", logo_url: "https://img.logo.dev/3plnet.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "AMS360", description: "Insurance agency management system", logo_url: "https://img.logo.dev/vertafore.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "ATM Manager Pro", description: "ATM management and monitoring software", logo_url: "https://img.logo.dev/atmmanagerpro.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Access Group", description: "Business management software for mid-market companies", logo_url: "https://img.logo.dev/theaccessgroup.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "AccountMate", description: "Accounting and business management software for small to mid-sized businesses", logo_url: "https://img.logo.dev/accountmate.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "AccountTech", description: "Accounting practice management software", logo_url: "https://img.logo.dev/accounttech.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "AccountView", description: "Web-based accounting solution for financial management", logo_url: "https://img.logo.dev/accountview.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "AccountingSeed", description: "Cloud-based accounting software built on Salesforce platform", logo_url: "https://img.logo.dev/accountingseed.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "AccountsIQ", description: "Cloud-based financial management and consolidation software", logo_url: "https://img.logo.dev/accountsiq.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Addepar", description: "Wealth management platform for investment data and analytics", logo_url: "https://img.logo.dev/addepar.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Aderant Financial", description: "Financial management software for law firms", logo_url: "https://img.logo.dev/aderant.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Advanced Manufacturing Control Systems (AMCS)", description: "ERP and operations management for waste and recycling industry", logo_url: "https://img.logo.dev/amcsgroup.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "AgilePlace", description: "Visual project management and workflow collaboration tool", logo_url: "https://img.logo.dev/agileplace.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Agvance", description: "Farm management and agribusiness software", logo_url: "https://img.logo.dev/sssinc.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Aims", description: "Business management software for various industries", logo_url: "https://img.logo.dev/aims360.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Alliant Systems", description: "Insurance agency management software", logo_url: "https://img.logo.dev/alliantsystems.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Alpine", description: "Project and portfolio management software", logo_url: "https://img.logo.dev/alpinesoftware.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Aparatix", description: "Accounting and business management software", logo_url: "https://img.logo.dev/aparatix.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Apex Trading", description: "Commodity trading and risk management software", logo_url: "https://img.logo.dev/apextrading.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "AppFolio", description: "Property management software for real estate", logo_url: "https://img.logo.dev/appfolio.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Applied Businees Solutions", description: "Insurance agency management software", logo_url: "https://img.logo.dev/appliedsystems.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Applied Epic", description: "Insurance agency management platform", logo_url: "https://img.logo.dev/appliedsystems.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Appx", description: "Business application development and management platform", logo_url: "https://img.logo.dev/appx.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Aps", description: "Advanced planning and scheduling software", logo_url: "https://img.logo.dev/aps.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Aptean", description: "Industry-specific ERP and supply chain software", logo_url: "https://img.logo.dev/aptean.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "As/400", description: "IBM midrange computer system (IBM i)", logo_url: "https://img.logo.dev/ibm.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Ascend PDI", description: "Retail management software for outdoor and bike shops", logo_url: "https://img.logo.dev/ascentbsi.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Aspire", description: "Business management software for landscape companies", logo_url: "https://img.logo.dev/aspiresoftware.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Athena", description: "Healthcare revenue cycle management and EHR system", logo_url: "https://img.logo.dev/athenahealth.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Auxilius", description: "Business management software", logo_url: "https://img.logo.dev/auxilius.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Avantage", description: "ERP software for distribution and manufacturing", logo_url: "https://img.logo.dev/advantagedatasystems.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Avanti HR", description: "Human resources management software", logo_url: "https://img.logo.dev/avantihr.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Aws S3", description: "Amazon cloud object storage service", logo_url: "https://img.logo.dev/aws.amazon.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Axon", description: "Law enforcement records management system", logo_url: "https://img.logo.dev/axon.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Axxerion", description: "Facility and asset management software", logo_url: "https://img.logo.dev/axxerion.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "B2W (Bid2Win)", description: "Construction bid management and estimating software", logo_url: "https://img.logo.dev/b2wsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "BambooHR", description: "Human resources information system for SMBs", logo_url: "https://img.logo.dev/bamboohr.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Bespoke Database", description: "Custom-built database solutions", logo_url: "", category: "IT & Data" },
  { name: "Bestnotes", description: "Behavioral health practice management and EHR", logo_url: "https://img.logo.dev/best-notes.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "BigData", description: "Large-scale data processing and analytics platforms", logo_url: "", category: "IT & Data" },
  { name: "BigTime", description: "Professional services automation and time tracking", logo_url: "https://img.logo.dev/bigtime.net?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Bill.com", description: "Accounts payable and receivable automation", logo_url: "https://img.logo.dev/bill.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Blackbaud", description: "Nonprofit and education management software", logo_url: "https://img.logo.dev/blackbaud.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Boulevard", description: "Client experience platform for appointment-based businesses", logo_url: "https://img.logo.dev/joinblvd.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "BreatheHR", description: "HR management software for small businesses", logo_url: "https://img.logo.dev/breathehr.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "BrightHR", description: "HR and payroll software for SMBs", logo_url: "https://img.logo.dev/brighthr.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Build Ops", description: "Field service management for contractors", logo_url: "https://img.logo.dev/buildops.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Build2Win", description: "Construction management and estimating software", logo_url: "https://img.logo.dev/build2win.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Builder Prime", description: "Construction project management for home builders", logo_url: "https://img.logo.dev/builderprime.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "BullHorn", description: "Applicant tracking and CRM for staffing", logo_url: "https://img.logo.dev/bullhorn.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Business First Financials", description: "Financial management software", logo_url: "https://img.logo.dev/businessfirstfinancials.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "CCC One", description: "Claims management software for auto insurance", logo_url: "https://img.logo.dev/cccis.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "CXone", description: "Cloud contact center and customer experience platform", logo_url: "https://img.logo.dev/nice.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Customer Service" },
  { name: "CaptivateIQ", description: "Sales commission management platform", logo_url: "https://img.logo.dev/captivateiq.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "CareSmartz360", description: "Home care management software", logo_url: "https://img.logo.dev/caresmartz.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "CareTend", description: "Home healthcare management platform", logo_url: "https://img.logo.dev/caretend.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "CargoWise", description: "Logistics and supply chain management software", logo_url: "https://img.logo.dev/cargowise.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Cb2", description: "Auto collision repair management software", logo_url: "https://img.logo.dev/cb2software.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Cema", description: "Business management software", logo_url: "https://img.logo.dev/cema.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "CentralReach", description: "Practice management software for ABA therapy", logo_url: "https://img.logo.dev/centralreach.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Ceridian Dayforce", description: "Cloud HCM platform for HR and payroll", logo_url: "https://img.logo.dev/ceridian.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Certify", description: "Expense management and invoice processing", logo_url: "https://img.logo.dev/certify.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Charthop", description: "People analytics and organizational planning", logo_url: "https://img.logo.dev/charthop.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Cin7", description: "Inventory and order management for product sellers", logo_url: "https://img.logo.dev/cin7.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Clockify", description: "Time tracking and timesheet management", logo_url: "https://img.logo.dev/clockify.me?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Computer Ease", description: "Construction accounting and project management", logo_url: "https://img.logo.dev/computerease.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Concept 1", description: "Architectural design and project management software", logo_url: "https://img.logo.dev/concept1.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Concept Integrated", description: "Business management software", logo_url: "https://img.logo.dev/conceptintegrated.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "ConnectWise", description: "Business management platform for technology solution providers", logo_url: "https://img.logo.dev/connectwise.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Connecteam", description: "Employee management app for deskless workers", logo_url: "https://img.logo.dev/connecteam.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Contpaqi", description: "Accounting and business management software for Mexico", logo_url: "https://img.logo.dev/contpaqi.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "CornerCloud", description: "Cloud-based business management software", logo_url: "https://img.logo.dev/cornercloud.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Coupa", description: "Spend management and procurement software", logo_url: "https://img.logo.dev/coupa.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "CrewTracks", description: "Time tracking for construction crews", logo_url: "https://img.logo.dev/crewtracks.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Crystal Reports (GSS)", description: "Business intelligence and reporting tool", logo_url: "https://img.logo.dev/sap.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "CubHub", description: "Cannabis compliance and operations software", logo_url: "https://img.logo.dev/cubhub.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Custom API", description: "Custom-built application programming interfaces", logo_url: "", category: "IT & Data" },
  { name: "Data Warehouse", description: "Centralized repository for business intelligence", logo_url: "", category: "IT & Data" },
  { name: "DataBricks", description: "Unified analytics platform for big data and AI", logo_url: "https://img.logo.dev/databricks.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Datacor", description: "ERP for chemical and process manufacturing", logo_url: "https://img.logo.dev/datacor.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Datafile", description: "Accounting and business management software", logo_url: "https://img.logo.dev/datafile.co.uk?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "DateV", description: "Accounting and tax software for Germany", logo_url: "https://img.logo.dev/datev.de?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Deacom", description: "ERP software for process manufacturers", logo_url: "https://img.logo.dev/deacom.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Deal Pack", description: "Deal and transaction management software", logo_url: "https://img.logo.dev/dealpack.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "DealCloud", description: "Deal management and business development CRM", logo_url: "https://img.logo.dev/dealcloud.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Deltek Vision", description: "Project-based ERP for professional services", logo_url: "https://img.logo.dev/deltek.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Deltek Workbook", description: "Project management and time tracking", logo_url: "https://img.logo.dev/deltek.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Deltex Costpoint", description: "Project accounting for government contractors", logo_url: "https://img.logo.dev/deltek.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Dentrix Enterprise", description: "Dental practice management software", logo_url: "https://img.logo.dev/dentrix.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "DepotNet", description: "Parts and service management for heavy equipment", logo_url: "https://img.logo.dev/depotnet.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Diomac SQL", description: "Business management software", logo_url: "https://img.logo.dev/diomac.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Dispatch", description: "Field service management software", logo_url: "https://img.logo.dev/dispatch.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Distru", description: "Cannabis ERP and seed-to-sale tracking", logo_url: "https://img.logo.dev/distru.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Dmp", description: "Dealership management platform for automotive", logo_url: "https://img.logo.dev/dmp.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "DockMaster", description: "Dock scheduling and warehouse management", logo_url: "https://img.logo.dev/dockmaster.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Domo", description: "Business intelligence and data visualization", logo_url: "https://img.logo.dev/domo.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "DropStat", description: "Cannabis compliance and tracking software", logo_url: "https://img.logo.dev/dropstat.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Droptop", description: "Cannabis retail and compliance software", logo_url: "https://img.logo.dev/droptop.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Dutchie", description: "Cannabis e-commerce and POS platform", logo_url: "https://img.logo.dev/dutchie.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Dynamics SL", description: "Microsoft project accounting and management ERP", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "E-Conomic", description: "Online accounting software for SMBs", logo_url: "https://img.logo.dev/e-conomic.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "E2", description: "Shop management software for job shops", logo_url: "https://img.logo.dev/shoptech.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Eclipse", description: "Distribution and supply chain ERP", logo_url: "https://img.logo.dev/eclipsesoftware.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Ecp", description: "Construction project management software", logo_url: "https://img.logo.dev/ecp.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Email", description: "Electronic mail communication system", logo_url: "", category: "Sales & Marketing" },
  { name: "Employment Hero", description: "HR and payroll platform for Australia/NZ", logo_url: "https://img.logo.dev/employmenthero.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Emsow", description: "Emergency management and incident tracking", logo_url: "https://img.logo.dev/emsow.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Encompass", description: "Mortgage lending platform", logo_url: "https://img.logo.dev/encompass.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Encompix", description: "ERP for engineer-to-order manufacturers", logo_url: "https://img.logo.dev/encompix.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Entrata", description: "Property management software for multifamily", logo_url: "https://img.logo.dev/entrata.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Eoc", description: "Emergency operations center software", logo_url: "https://img.logo.dev/eoc.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Epic", description: "Electronic health records system for healthcare", logo_url: "https://img.logo.dev/epic.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Evolution M", description: "Apparel and footwear ERP software", logo_url: "https://img.logo.dev/evolutionm.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Exact", description: "Business software for SMBs in Europe", logo_url: "https://img.logo.dev/exact.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Exact Online", description: "Cloud-based business software", logo_url: "https://img.logo.dev/exact.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Expert Contab", description: "Accounting software for France", logo_url: "https://img.logo.dev/expertcontab.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "FIS/Enterprise Accounting System", description: "Banking and financial technology solutions", logo_url: "https://img.logo.dev/fisglobal.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "FiServ Precision", description: "Core banking software", logo_url: "https://img.logo.dev/fiserv.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Fifth Third Bank", description: "Banking and financial services", logo_url: "https://img.logo.dev/53.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Filemaker", description: "Low-code database and app development platform", logo_url: "https://img.logo.dev/claris.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Files.com", description: "Cloud file transfer and storage platform", logo_url: "https://img.logo.dev/files.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Financial Force", description: "Cloud ERP and PSA built on Salesforce", logo_url: "https://img.logo.dev/financialforce.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Fishbowl", description: "Inventory management and manufacturing software", logo_url: "https://img.logo.dev/fishbowlinventory.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Fleetio", description: "Fleet maintenance management software", logo_url: "https://img.logo.dev/fleetio.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Flexi", description: "Workforce management software", logo_url: "https://img.logo.dev/flexi.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Forward Computers Limited", description: "Business management software", logo_url: "https://img.logo.dev/forwardcomputers.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Foundation Software", description: "Construction accounting and project management", logo_url: "https://img.logo.dev/foundationsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Fourth Shift", description: "Manufacturing ERP software", logo_url: "https://img.logo.dev/infor.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "FrameworksLTC", description: "Long-term care management software", logo_url: "https://img.logo.dev/frameworksltc.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Fresh Byte", description: "Produce traceability and inventory management", logo_url: "https://img.logo.dev/freshbyte.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Fresh Projects", description: "Project management and collaboration tool", logo_url: "https://img.logo.dev/freshprojects.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Fresh Service", description: "IT service management software", logo_url: "https://img.logo.dev/freshservice.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Fuels Manager", description: "Fuel management and inventory tracking", logo_url: "https://img.logo.dev/fuelsmanager.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Fund EZ", description: "Fund accounting software for nonprofits", logo_url: "https://img.logo.dev/fundez.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Global Shop", description: "Shop floor management for manufacturing", logo_url: "https://img.logo.dev/globalshopsolutions.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Go High Level", description: "All-in-one marketing and CRM platform", logo_url: "https://img.logo.dev/gohighlevel.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Google Analytics", description: "Web analytics and reporting platform", logo_url: "https://img.logo.dev/google.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Google Big Query", description: "Cloud data warehouse for analytics", logo_url: "https://img.logo.dev/google.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Google Sheets", description: "Online spreadsheet application", logo_url: "https://img.logo.dev/google.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "General Business" },
  { name: "Greenhouse", description: "Applicant tracking and recruiting software", logo_url: "https://img.logo.dev/greenhouse.io?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Grow POS", description: "Point of sale system", logo_url: "https://img.logo.dev/growpos.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "GrowFlow", description: "Cannabis compliance and inventory management", logo_url: "https://img.logo.dev/growflow.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Gusto", description: "Payroll and HR platform for small businesses", logo_url: "https://img.logo.dev/gusto.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Harvest", description: "Time tracking and invoicing for teams", logo_url: "https://img.logo.dev/getharvest.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Hashavit (חשבית)", description: "Accounting software for Israel", logo_url: "https://img.logo.dev/hashavit.co.il?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Hashavshevet", description: "Accounting software for Israel", logo_url: "https://img.logo.dev/hashavshevet.co.il?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Hcss", description: "Construction software for heavy civil contractors", logo_url: "https://img.logo.dev/hcss.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "HiBob", description: "HR platform for modern businesses", logo_url: "https://img.logo.dev/hibob.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Hive", description: "Project management and collaboration platform", logo_url: "https://img.logo.dev/hive.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "HomeDev", description: "Property development management software", logo_url: "https://img.logo.dev/homedev.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Homecare Homebase", description: "Home health and hospice software", logo_url: "https://img.logo.dev/hchb.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Horizon", description: "Banking core processing system", logo_url: "https://img.logo.dev/finastra.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Hsbc", description: "Global banking and financial services", logo_url: "https://img.logo.dev/hsbc.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Humaans", description: "HR information system for modern companies", logo_url: "https://img.logo.dev/humaans.io?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "IPS Inova", description: "ERP for food and beverage manufacturers", logo_url: "https://img.logo.dev/ipsinova.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "IPlicit", description: "Cloud financial management for mid-market", logo_url: "https://img.logo.dev/iplicit.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Ifs ERP", description: "Enterprise resource planning for service industries", logo_url: "https://img.logo.dev/ifs.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "InMass", description: "Media asset management software", logo_url: "https://img.logo.dev/inmass.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "InfinityQS", description: "Quality management software for manufacturing", logo_url: "https://img.logo.dev/infinityqs.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Input Health", description: "Healthcare data integration platform", logo_url: "https://img.logo.dev/inputhealth.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Insperity HR", description: "HR outsourcing and business solutions", logo_url: "https://img.logo.dev/insperity.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Intuit ERP", description: "Business management software by Intuit", logo_url: "https://img.logo.dev/intuit.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Investran", description: "Private equity and investment management software", logo_url: "https://img.logo.dev/investran.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "JobBoss", description: "Job shop management software", logo_url: "https://img.logo.dev/jobboss.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Jobber", description: "Home service business management software", logo_url: "https://img.logo.dev/getjobber.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Jobscope", description: "ERP for job shops and contract manufacturers", logo_url: "https://img.logo.dev/jobscope.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Jonas ERP", description: "ERP for construction and service industries", logo_url: "https://img.logo.dev/jonassoftware.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Juniper Square", description: "Investment management platform for real estate", logo_url: "https://img.logo.dev/junipersquare.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "JustWorks", description: "Payroll and HR platform for businesses", logo_url: "https://img.logo.dev/justworks.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Juvonno EMR", description: "Practice management for healthcare practitioners", logo_url: "https://img.logo.dev/juvonno.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "K2", description: "Workflow automation and process management", logo_url: "https://img.logo.dev/k2.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Karmak Fusion", description: "Business management for commercial truck dealers", logo_url: "https://img.logo.dev/karmak.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "KnowBe4", description: "Security awareness training platform", logo_url: "https://img.logo.dev/knowbe4.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Leaflink", description: "B2B wholesale platform for cannabis", logo_url: "https://img.logo.dev/leaflink.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Legacy", description: "Legacy system or custom-built software", logo_url: "", category: "General Business" },
  { name: "Lightspeed", description: "Cloud POS and e-commerce platform", logo_url: "https://img.logo.dev/lightspeedhq.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Logics", description: "Business management software", logo_url: "https://img.logo.dev/logics.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Logistech", description: "Transportation and logistics management", logo_url: "https://img.logo.dev/logistech.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Looker", description: "Business intelligence and data analytics", logo_url: "https://img.logo.dev/looker.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "M1", description: "Manufacturing ERP software", logo_url: "https://img.logo.dev/m1.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "M3 Accounting", description: "Accounting software solution", logo_url: "https://img.logo.dev/m3accounting.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "MIP Abila", description: "Fund accounting for nonprofits and government", logo_url: "https://img.logo.dev/abila.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "MRI Software", description: "Real estate software for property management", logo_url: "https://img.logo.dev/mrisoftware.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Macola", description: "ERP software for distribution and manufacturing", logo_url: "https://img.logo.dev/macola.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Made2Manage", description: "Manufacturing ERP system", logo_url: "https://img.logo.dev/aptean.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Margin Edge", description: "Restaurant management and accounting platform", logo_url: "https://img.logo.dev/marginedge.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Marksystems", description: "Apparel and footwear ERP", logo_url: "https://img.logo.dev/marksystems.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Mattmin", description: "Accounting and business management", logo_url: "https://img.logo.dev/mattmin.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Maxio", description: "Subscription billing and revenue management", logo_url: "https://img.logo.dev/maxio.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Maytas", description: "Business management software", logo_url: "https://img.logo.dev/maytas.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Mcleod", description: "Transportation management software", logo_url: "https://img.logo.dev/mcleodsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Merit", description: "Medical billing and practice management", logo_url: "https://img.logo.dev/meritbilling.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Metabase", description: "Open-source business intelligence tool", logo_url: "https://img.logo.dev/metabase.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Metrc", description: "Cannabis compliance and traceability system", logo_url: "https://img.logo.dev/metrc.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Mews", description: "Hotel property management system", logo_url: "https://img.logo.dev/mews.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "MicroStrategy", description: "Enterprise analytics and mobility platform", logo_url: "https://img.logo.dev/microstrategy.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Micros", description: "Point of sale and hospitality management", logo_url: "https://img.logo.dev/oracle.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Mindshare", description: "Media planning and buying software", logo_url: "https://img.logo.dev/mindshare.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Mintsoft", description: "Warehouse management system", logo_url: "https://img.logo.dev/mintsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Motive", description: "Fleet management and compliance platform", logo_url: "https://img.logo.dev/gomotive.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Move IT", description: "Managed file transfer software", logo_url: "https://img.logo.dev/moveit.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "MySQL", description: "Open-source relational database", logo_url: "https://img.logo.dev/mysql.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "NXT Wash", description: "Car wash management software", logo_url: "https://img.logo.dev/nxtwash.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Navan", description: "Corporate travel and expense management", logo_url: "https://img.logo.dev/navan.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Naviga", description: "Media management software for publishers", logo_url: "https://img.logo.dev/navigaglobal.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "NetYield", description: "Financial planning and analysis software", logo_url: "https://img.logo.dev/netyield.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Nexius", description: "Business management software", logo_url: "https://img.logo.dev/nexius.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Nexomia", description: "ERP for wholesale distribution", logo_url: "https://img.logo.dev/nexomia.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "NextGen", description: "Healthcare IT solutions and EHR", logo_url: "https://img.logo.dev/nextgen.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Ng ERP", description: "Enterprise resource planning software", logo_url: "https://img.logo.dev/ngerp.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "NikoHealth", description: "Healthcare practice management", logo_url: "https://img.logo.dev/nikohealth.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "OSS (Enverus)", description: "Oil and gas software and data analytics", logo_url: "https://img.logo.dev/enverus.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Odoo", description: "Open-source ERP and business applications", logo_url: "https://img.logo.dev/odoo.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "OnPay", description: "Payroll and HR software for small business", logo_url: "https://img.logo.dev/onpay.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "OneDrive", description: "Cloud storage and file sharing service", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "OneOffice", description: "Business management software", logo_url: "https://img.logo.dev/oneoffice.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Opendental", description: "Dental practice management software", logo_url: "https://img.logo.dev/opendental.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Opera 3 (Visual Fox Pro)", description: "Accounting software on legacy platform", logo_url: "https://img.logo.dev/pegasus.co.uk?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Operating Management System (OMS)", description: "Operations and order management system", logo_url: "", category: "Operations & Supply Chain" },
  { name: "Orion", description: "Asset management and portfolio tracking", logo_url: "https://img.logo.dev/orion.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "OutSystems", description: "Low-code application development platform", logo_url: "https://img.logo.dev/outsystems.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "P21", description: "Distribution ERP software", logo_url: "https://img.logo.dev/p21.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "PCRecruiter", description: "Applicant tracking system for recruiting", logo_url: "https://img.logo.dev/pcrecruiter.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "PS Financials", description: "Public sector financial management", logo_url: "https://img.logo.dev/psfinancials.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Pace", description: "Retail management software", logo_url: "https://img.logo.dev/pace.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Parallax", description: "Financial planning software", logo_url: "https://img.logo.dev/parallax.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Passport", description: "Parking management and enforcement platform", logo_url: "https://img.logo.dev/passportparking.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Paycom", description: "Payroll and HR technology", logo_url: "https://img.logo.dev/paycom.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Paycor", description: "HR and payroll software", logo_url: "https://img.logo.dev/paycor.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Paylocity", description: "Cloud-based payroll and HCM", logo_url: "https://img.logo.dev/paylocity.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Payworks", description: "Payroll and HR software for Canada", logo_url: "https://img.logo.dev/payworks.ca?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Pegasus", description: "Business management software", logo_url: "https://img.logo.dev/pegasus.co.uk?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Pentagon", description: "Construction project management", logo_url: "https://img.logo.dev/pentagon2000.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "People 2.0", description: "Staffing and recruiting software", logo_url: "https://img.logo.dev/people2.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "People XD", description: "HR management and analytics platform", logo_url: "https://img.logo.dev/peoplexd.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "PeopleFirst", description: "HR management software", logo_url: "https://img.logo.dev/peoplefirst.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "PeopleSoft", description: "Enterprise HR and financial management", logo_url: "https://img.logo.dev/oracle.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Perfect Gym", description: "Gym and fitness club management software", logo_url: "https://img.logo.dev/perfectgym.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Pest Pack", description: "Pest control business management software", logo_url: "https://img.logo.dev/pestpac.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Pixid", description: "Digital asset management software", logo_url: "https://img.logo.dev/pixid.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Plex", description: "Manufacturing execution system and ERP", logo_url: "https://img.logo.dev/plex.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Plexxis", description: "Construction management software", logo_url: "https://img.logo.dev/plexxis.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Portal", description: "Web-based access gateway or platform", logo_url: "", category: "IT & Data" },
  { name: "PostgreSQL", description: "Open-source relational database system", logo_url: "https://img.logo.dev/postgresql.org?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Power BI", description: "Business analytics and visualization tool", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "PowerPro", description: "Business management software", logo_url: "https://img.logo.dev/powerpro.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Prima", description: "Insurance software platform", logo_url: "https://img.logo.dev/prima.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Priority", description: "ERP software for manufacturing and distribution", logo_url: "https://img.logo.dev/priority-software.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "PrismHR", description: "HR and payroll software for PEOs", logo_url: "https://img.logo.dev/prismhr.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "ProCrew", description: "Workforce management for field services", logo_url: "https://img.logo.dev/procrew.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Procee", description: "Business process management software", logo_url: "https://img.logo.dev/procee.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Proceed Software", description: "Construction project management", logo_url: "https://img.logo.dev/proceedsoftware.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Procore", description: "Construction project management platform", logo_url: "https://img.logo.dev/procore.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "ProfitKey", description: "ERP for distribution companies", logo_url: "https://img.logo.dev/profitkey.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "ProgressSQL", description: "Relational database management system", logo_url: "https://img.logo.dev/progress.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Prophix", description: "Corporate performance management software", logo_url: "https://img.logo.dev/prophix.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Prospect 365", description: "CRM and business management for distribution", logo_url: "https://img.logo.dev/prospect365.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Provident", description: "Business management software", logo_url: "https://img.logo.dev/provident.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Qlik", description: "Data analytics and business intelligence", logo_url: "https://img.logo.dev/qlik.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Qualifacts", description: "Behavioral health EHR and practice management", logo_url: "https://img.logo.dev/qualifacts.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Quantum", description: "Business management software", logo_url: "https://img.logo.dev/quantum.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Quickbase", description: "Low-code application development platform", logo_url: "https://img.logo.dev/quickbase.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Quickmar", description: "Marketing automation software", logo_url: "https://img.logo.dev/quickmar.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Quipware", description: "Business software solutions", logo_url: "https://img.logo.dev/quipware.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Raken", description: "Construction field management software", logo_url: "https://img.logo.dev/rakenapp.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Ramp", description: "Corporate card and expense management", logo_url: "https://img.logo.dev/ramp.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Real Green", description: "Lawn care and pest control software", logo_url: "https://img.logo.dev/realgreen.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "RealPage", description: "Property management software for multifamily", logo_url: "https://img.logo.dev/realpage.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Redshift", description: "Cloud data warehouse by Amazon", logo_url: "https://img.logo.dev/aws.amazon.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Redsky", description: "Emergency communications and E911 solutions", logo_url: "https://img.logo.dev/redsky.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Regent Bank", description: "Banking and financial services", logo_url: "https://img.logo.dev/regentbank.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Rent Manager", description: "Property management software", logo_url: "https://img.logo.dev/rentmanager.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Research Monitor", description: "Research management software", logo_url: "https://img.logo.dev/researchmonitor.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Residex", description: "Property management software", logo_url: "https://img.logo.dev/residex.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Resman", description: "Multifamily property management platform", logo_url: "https://img.logo.dev/resman.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Restaurant 365", description: "Restaurant management and accounting", logo_url: "https://img.logo.dev/restaurant365.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Rev.io", description: "Subscription billing and revenue management", logo_url: "https://img.logo.dev/rev.io?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Rfms", description: "Retail and franchise management system", logo_url: "https://img.logo.dev/rfms.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Ridder", description: "Horticulture business management software", logo_url: "https://img.logo.dev/ridder.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Right Angle", description: "Commodity trading and risk management", logo_url: "https://img.logo.dev/iorightangle.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Rimas", description: "Business management software", logo_url: "https://img.logo.dev/rimas.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Rippling", description: "HR, IT, and finance automation platform", logo_url: "https://img.logo.dev/rippling.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Rota Ready", description: "Workforce management and scheduling", logo_url: "https://img.logo.dev/rotaready.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Ryznware", description: "Construction management software", logo_url: "https://img.logo.dev/ryznware.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "SQL Server", description: "Microsoft relational database management", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Sai", description: "Business management software", logo_url: "https://img.logo.dev/sai.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Scrap Dragon", description: "Scrap yard management software", logo_url: "https://img.logo.dev/scrapdragon.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Seradex", description: "Manufacturing ERP software", logo_url: "https://img.logo.dev/seradex.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Service Trade", description: "Commercial contractor management software", logo_url: "https://img.logo.dev/servicetrade.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "ServiceCore", description: "Field service management for waste industry", logo_url: "https://img.logo.dev/servicecore.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "ServiceTitan", description: "Field service management for home services", logo_url: "https://img.logo.dev/servicetitan.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Sftp", description: "Secure file transfer protocol", logo_url: "", category: "IT & Data" },
  { name: "SharePoint", description: "Document management and collaboration", logo_url: "https://img.logo.dev/microsoft.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "General Business" },
  { name: "ShotGrid", description: "Project management for media and entertainment", logo_url: "https://img.logo.dev/autodesk.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Sigma", description: "Cloud analytics and business intelligence", logo_url: "https://img.logo.dev/sigmacomputing.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Simpli.fi", description: "Advertising automation platform", logo_url: "https://img.logo.dev/simpli.fi?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Skubana", description: "Multichannel e-commerce operations platform", logo_url: "https://img.logo.dev/skubana.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Smartsheet", description: "Work management and automation platform", logo_url: "https://img.logo.dev/smartsheet.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Snowflake", description: "Cloud data warehouse platform", logo_url: "https://img.logo.dev/snowflake.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Softpack", description: "Business management software", logo_url: "https://img.logo.dev/softpack.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Soldo", description: "Expense management and corporate cards", logo_url: "https://img.logo.dev/soldo.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Sona", description: "Scheduling and participant management for research", logo_url: "https://img.logo.dev/sona-systems.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Spectrum Viewpoint", description: "Construction ERP software", logo_url: "https://img.logo.dev/viewpoint.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Spiff", description: "Sales commission automation platform", logo_url: "https://img.logo.dev/spiff.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Spins", description: "Retail analytics for natural products", logo_url: "https://img.logo.dev/spins.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Spruce", description: "Healthcare communication platform", logo_url: "https://img.logo.dev/sprucehealth.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Square", description: "Payment processing and POS system", logo_url: "https://img.logo.dev/squareup.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "Sscs", description: "Business management software", logo_url: "https://img.logo.dev/sscs.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Streak", description: "CRM integrated with Gmail", logo_url: "https://img.logo.dev/streak.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Stripe", description: "Online payment processing platform", logo_url: "https://img.logo.dev/stripe.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Striven", description: "Cloud-based ERP and business management", logo_url: "https://img.logo.dev/striven.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Sugar", description: "CRM platform for customer experience", logo_url: "https://img.logo.dev/sugarcrm.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Sun Systems", description: "Financial management software", logo_url: "https://img.logo.dev/infor.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "SurePoint", description: "Insurance agency management software", logo_url: "https://img.logo.dev/surepoint.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Syspro", description: "ERP for manufacturing and distribution", logo_url: "https://img.logo.dev/syspro.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Syteline", description: "Manufacturing ERP software", logo_url: "https://img.logo.dev/infor.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "T21", description: "Fashion and apparel ERP software", logo_url: "https://img.logo.dev/t21solutions.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Retail & E-commerce" },
  { name: "TMW Suite", description: "Transportation management system", logo_url: "https://img.logo.dev/tmwsystems.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "TOPdesk", description: "Service management software", logo_url: "https://img.logo.dev/topdesk.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Tableau", description: "Visual analytics and business intelligence", logo_url: "https://img.logo.dev/tableau.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Tagetik", description: "Corporate performance management", logo_url: "https://img.logo.dev/tagetik.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" },
  { name: "Tally", description: "Accounting and inventory management", logo_url: "https://img.logo.dev/tallysolutions.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Tekmetric", description: "Auto repair shop management software", logo_url: "https://img.logo.dev/tekmetric.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Tempest", description: "Business management software", logo_url: "https://img.logo.dev/tempest.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "The Mortgage Office", description: "Mortgage origination software", logo_url: "https://img.logo.dev/themortgageoffice.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Tipalti", description: "Accounts payable automation", logo_url: "https://img.logo.dev/tipalti.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Titan", description: "Business management software", logo_url: "https://img.logo.dev/titan.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Toast", description: "Restaurant POS and management platform", logo_url: "https://img.logo.dev/toasttab.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Touchpoint", description: "Business management software", logo_url: "https://img.logo.dev/touchpoint.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "TrackerRMS", description: "Recruitment software for staffing agencies", logo_url: "https://img.logo.dev/tracker-rms.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Traverse", description: "Accounting and business management software", logo_url: "https://img.logo.dev/traverse.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Trex", description: "Healthcare revenue cycle management", logo_url: "https://img.logo.dev/trexhealth.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "True", description: "Business management software", logo_url: "https://img.logo.dev/true.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Tulip", description: "Manufacturing operations platform", logo_url: "https://img.logo.dev/tulip.co?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Twinfield", description: "Cloud accounting software for Europe", logo_url: "https://img.logo.dev/twinfield.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "UKG Ready (Kronos)", description: "Workforce management and HCM", logo_url: "https://img.logo.dev/ukg.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "UKG Ultipro", description: "HR and payroll cloud platform", logo_url: "https://img.logo.dev/ukg.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Ukg", description: "Human capital management solutions", logo_url: "https://img.logo.dev/ukg.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Unanet", description: "Project-based ERP for government contractors", logo_url: "https://img.logo.dev/unanet.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Unik", description: "Business management software", logo_url: "https://img.logo.dev/unik.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "Unleashed", description: "Cloud inventory management software", logo_url: "https://img.logo.dev/unleashedsoftware.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "VIP Software", description: "Wholesale distribution ERP", logo_url: "https://img.logo.dev/vipsoftware.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "VantagePoint", description: "Project management for A&E firms", logo_url: "https://img.logo.dev/deltek.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Velocity", description: "ERP for process manufacturing", logo_url: "https://img.logo.dev/velocity.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Vicinity Brew", description: "Brewery management software", logo_url: "https://img.logo.dev/vicinitybrew.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "ViewPoint Vista", description: "Construction ERP software", logo_url: "https://img.logo.dev/viewpoint.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "VinSolutions", description: "Automotive CRM and dealership software", logo_url: "https://img.logo.dev/vinsolutions.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Visual", description: "ERP for manufacturing", logo_url: "https://img.logo.dev/infor.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Visual Produce", description: "Produce traceability and accounting", logo_url: "https://img.logo.dev/visualproduce.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "WCBS Pass", description: "Parking management software", logo_url: "https://img.logo.dev/wcbs.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "WelcomeHome", description: "Property management software", logo_url: "https://img.logo.dev/welcomehome.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Wellsky", description: "Healthcare technology and data solutions", logo_url: "https://img.logo.dev/wellsky.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "Welltrax", description: "Employee wellness platform", logo_url: "https://img.logo.dev/welltrax.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Specialized Industry" },
  { name: "WorkMax", description: "Field service management software", logo_url: "https://img.logo.dev/workmax.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Workamajig", description: "Project management for creative agencies", logo_url: "https://img.logo.dev/workamajig.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "Workday", description: "Enterprise cloud applications for finance and HR", logo_url: "https://img.logo.dev/workday.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Workguru", description: "Job management and quoting software", logo_url: "https://img.logo.dev/workguru.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "XLedger", description: "Cloud accounting for mid-market companies", logo_url: "https://img.logo.dev/xledger.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Xero", description: "Cloud-based accounting software for small business", logo_url: "https://img.logo.dev/xero.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Yardi", description: "Property management and investment software", logo_url: "https://img.logo.dev/yardi.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Real Estate & Construction" },
  { name: "Younium", description: "Subscription management and billing", logo_url: "https://img.logo.dev/younium.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Finance & Accounting" },
  { name: "Zenefits", description: "HR software platform for small businesses", logo_url: "https://img.logo.dev/zenefits.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "Zendesk", description: "Customer service and engagement platform", logo_url: "https://img.logo.dev/zendesk.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Customer Service" },
  { name: "Zoho", description: "Suite of business software applications", logo_url: "https://img.logo.dev/zoho.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Productivity" },
  { name: "Zoho CRM", description: "Customer relationship management software", logo_url: "https://img.logo.dev/zoho.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Sales & Marketing" },
  { name: "Zoho Desk", description: "Customer support and help desk software", logo_url: "https://img.logo.dev/zoho.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Customer Service" },
  { name: "Zoho Inventory", description: "Inventory and order management software", logo_url: "https://img.logo.dev/zoho.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Operations & Supply Chain" },
  { name: "Zoho People", description: "Cloud HR management software", logo_url: "https://img.logo.dev/zoho.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Human Resources" },
  { name: "eCMS", description: "Case management software", logo_url: "https://img.logo.dev/ecms.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "Professional Services" },
  { name: "eLite ERP", description: "ERP for distribution and manufacturing", logo_url: "https://img.logo.dev/eliteerp.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "ERP" },
  { name: "iSeries", description: "IBM midrange computing platform", logo_url: "https://img.logo.dev/ibm.com?token=pk_NzP1pbRpRgeYlq-Gd1JtfQ", category: "IT & Data" }
];

export const INTEGRATIONS: Integration[] = rawData.map((item, index) => ({
  id: String(index + 1),
  name: item.name,
  description: item.description,
  longDescription: item.description, 
  category: item.category,
  logoColor: getColor(item.name),
  logoInitials: item.name.substring(0, 2).toUpperCase(),
  logoUrl: item.logo_url,
  popular: POPULAR_NAMES.has(item.name),
  tags: [item.category.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-'), 'integration']
})); 

const uniqueCategories = Array.from(new Set(rawData.map(i => i.category))).sort();
export const CATEGORIES: string[] = ['All', ...uniqueCategories];